name: IMHCNH
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13.5
  - pip
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - jupyter
  - notebook
  - matplotlib
  - dbfread
  - pip:
      - xgboost
      - shap
      - torch==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - torchaudio==2.7.1+cu128
      - --extra-index-url https://download.pytorch.org/whl/cu128
